### ISSUE TITLE
omni complete definitions not loaded 

### ISSUE THREAD

**Issue by megaannum** [jlc/envim#4]
After starting envim, omnicomplete does not work. 
If I manually enter:
:set omnifunc=envim#Completions
:set completeopt=menuone,preview
then omnicomplete works.

**Comment by megaannum** [comment]
if the following is placed in the ftplugin/scala.vim file
echo("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
the XXX... is not printed out to the vim cmd line (that I can see).

**Comment by jlc** [comment]
This issue appeared because Vim does not recognize the filetype of scala files, and then doesn't load the corresponding filetype plugin (envim/ftplugin/scala.vim).

It is now fixed in branch master by adding ftdetect/scala.vim.

A complementary option is to use vim-scala-behaghel (https://github.com/behaghel/vim-scala) which also provide scala syntax highlighting.

Thanks for reporting it!
